#!/bin/bash

: "${ORG:=pelican_platform}"
: "${INAME:=port-redirector}"
: "${TAG:=latest}"

if command -v podman &>/dev/null; then
    docker=podman
elif command -v docker &>/dev/null; then
    docker=docker
else
    echo >&2 "Neither docker nor podman were found"
    exit 127
fi


$docker build -t "${ORG}/${INAME}:${TAG}" .


# vim:ft=bash
